name: Simple Push Test

on:
  workflow_dispatch:

jobs:
  test-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Make a trivial change
      run: |
        echo "Test push" >> test.txt

    - name: Commit and Push
      run: |
        git config --local user.email "actions@users.noreply.github.com"
        git config --local user.name "GitHub Actions"
        git add .
        git commit -m "Your commit message"
        git push --set-upstream origin HEAD:feature --force
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
